### ISSUE TITLE
Windows 10 top bar is black

### ISSUE THREAD

**Issue by mohabo08** [0x7c13/UnityEditor-DarkMode#12]
In all the pictures I see of this plugin, the top bar (the one with minimize, close window, etc.) is a nice gray color that fits with the rest of the unity dark theme. This is the case for me as well, but only when the window doesn't have the focus. When it does have the focus, the top bar is completely black. I should also mention I'm on windows 10, I'm not sure if that makes a difference.

![1](https://github.com/user-attachments/assets/4a55de63-9a28-47e2-8e06-1418cbece173)
![2](https://github.com/user-attachments/assets/c73e3210-c683-4a3f-bed4-50a5b4d31e7c)

**Comment by 0x7c13** [comment]
What's your title bar color settings? That might be the cause.

**Comment by mohabo08** [comment]
Apparently the default windows 10 title bar is straight up black. The only way to change it is by changing the accent color for the whole system and applying it to the title bar.
