### ISSUE TITLE
Menus are white

### ISSUE THREAD

**Issue by Askhento** [0x7c13/UnityEditor-DarkMode#6]
Thank you for the work!
Is it possible to change menu to dark also?

![image](https://github.com/0x7c13/UnityEditor-DarkMode/assets/34323808/ed304151-4d82-4ddb-8945-c80bd901483c)

**Comment by 0x7c13** [comment]
Restart your editor after first installation

**Comment by Askhento** [comment]
Thanks! 
Closing.
