### ISSUE TITLE
Doesn't work fully on Unity 2019.2.21f1

### ISSUE THREAD

**Issue by adokova** [0x7c13/UnityEditor-DarkMode#9]
It seems to change the tabs at the top but the rest remain white themed

I'm on Windows 10

![Unity_WMLsTGUc24](https://github.com/user-attachments/assets/e939c774-1175-4db8-af2f-f622707efa70)

**Comment by 0x7c13** [comment]
You need to change your Unity theme to dark:
https://support.unity.com/hc/en-us/articles/115004982743-How-can-I-change-my-Editor-theme#:~:text=Launch%20the%20Unity%20Hub%20and,Light%20depending%20on%20your%20preference.
